# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'WIKADOMERACKA-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID:

menu:
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link:  'https://instagram.com/wikadomeracka'}
- {icon: 'envelope', link:   'mailto:w.b.domeracka@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

